version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=8.3
        - NODE_VERSION=22.14.0
    volumes:
      - ./src:/var/www/html/app
    environment:
      - APP_NAME=FileManageSystem
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:OxLS7A2qOvxcwW3tJZ9PS8q0ORTIrZ8lneZ/iVUcuas=
      - APP_LOCALE=ja
      - APP_FALLBACK_LOCALE=ja
      - APP_FAKER_LOCALE=ja_JP
      - APP_TIMEZONE=Asia/Tokyo
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_pass
      - SESSION_DRIVER=redis
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=laravel_db
      - POSTGRES_USER=laravel_user
      - POSTGRES_PASSWORD=laravel_pass
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
