version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=8.3
        - NODE_VERSION=22.14.0
    volumes:
      - ./src:/var/www/html/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=laravel_db
      - POSTGRES_USER=laravel_user
      - POSTGRES_PASSWORD=laravel_pass
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
